#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell such as ksh or
#       bash, then to use that shell, set the "SHELL" variable in your
#       environment in your home directory's .bashrc (or similar) and export it
#       in your current shell:
#
#           export SHELL=/bin/ksh
#           cd /path/to/Chick
#           ./gradlew <arg>...
#
#       Cygwin tries to symlink /bin/sh to Cygwin's bash, and this will fail.
#
#   (2) Runs this script from within the Chick directory only and all its dependencies
#       rely on your PATH setting to find the tools.
#
#   Alternatively, you can set the JVM_OPTS environment variable to pass JVM options to this script
#   and all other scripts which use it, like javac, jar, etc.
#
#   As an alternative to calling "gradlew gradleBuild" like: gradle, you can use it like this:
#
#        source env.sh; gradle gradleBuild
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
export APP_BASE_NAME
APP_HOME=$(CDPATH= cd "${APP_HOME}" && pwd -P) || exit
export APP_HOME

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

err () {
    echo "$*"
} >&2

if [ -z "$JAVA_HOME" ] ; then
    is_osx=false
    case "$(uname)" in #(
      CYGWIN* )         is_cygwin=true  ;; #(
      Darwin* )         is_osx=true     ;; #(
      MSYS* | MINGW* )  is_msys=true    ;; #(
      NOTO* )           is_noto=true    ;; #(
    esac

    if [ -z "$JAVA_HOME" ] ; then
      if [ -x /usr/libexec/java_home ]; then
        export JAVA_HOME=$(/usr/libexec/java_home)
      else
        export JAVA_HOME=/usr/lib/jvm/java-latest-openjdk
      fi
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$noto" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) 2>/dev/null ) || MAX_FD=maximum
        ;;
    esac
    # shellcheck disable=SC3045
    ulimit -n $MAX_FD
fi

# Collect all arguments for the java command, stacking in reverse order:
count=0
for arg in "$@"
do
    count=$(( $count + 1 ))
    eval "args$count=\\"$arg\\""
done
eval "set -- $(seq $count -1 1 | sed 's/^/\${args/;s/$}//')"

# Translate cygwin arguments to POSIX language.
if $cygwin ; then
    set -- $(echo "$@" | tr '\n' ' ' | sed -e 's/[{}]//g')
fi

case $( uname ) in                #((
SunOS* )
    # POSIX: print the working directory name with all symlinks resolved.
    prpath=$( resolve_symlink "$0" )
    cd "$( dirname "$prpath" )" || exit
    prpath=$( pwd -P )
    # Solaris sh will print the path, thus prepend a "./"
    if [ "$1" != '/' ]; then
        prpath="./$prpath"
    fi
    ;; #(
*CYGWIN* )
    set -a CLASSPATH
    for jarfile in "$APP_HOME"/gradle/wrapper/*.jar
    do
      set -a CLASSPATH=$CLASSPATH:$jarfile
    done
    set +a
    ;;
esac

APP_HOME_CLASSPATH=
[ "$CLASSPATH" ] && APP_HOME_CLASSPATH="$CLASSPATH"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=" \\
-Xmx64m \\
-Xms64m"

if [ "$JAVA_TOOL_OPTIONS" ] ; then
    DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTIONS $JAVA_TOOL_OPTIONS"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS -classpath "$APP_HOME_CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
